### Title : Bio Informatics : Hidden Messages in the Replication Origin
### Author : Kuldeep Thakre
### 13/06/2020
###


def DynamicPatterns(dna,MaxK):
    Map = {}
    Max = 0
    for x in range(0,len(dna)-MaxK):
        if(Count(dna, dna[x:x+MaxK]) >= 3):
            if dna[x:x+MaxK] in Map:
                Map[dna[x:x+MaxK]] += 1
            else:
                Map.setdefault(dna[x:x+MaxK], 1)
    string = ""
    Max = max(Map.values())
    for x in Map:
        if Map[x] == Max:
            string += x
            string += " "

    print(string)

def Count(dna, pattern):
    k = len(pattern)
    matches = 0

    for x in range(0, len(dna)):
        if dna[x] == pattern[0]:
            if(str(dna[x:x+k]) == pattern):
                matches += 1
    return matches

DNA = "ACTTTAGTTAACCGGTGCGCTGACGTAACCGGTGGTGTCCGTCGCTGACGGTGTCCGTTAACCGGTGTAACCGGTGTAACCGGTGGTGTCCGTTAACCGGTGGGTGCTCATACTTTAGTACTTTAGTACTTTAGTACTTTAGTGGTGCTCATTAACCGGTGCGCTGACGCGCTGACGTAACCGGTGTAACCGGTGGTGTCCGTACTTTAGTGTGTCCGTACTTTAGTCGCTGACGCGCTGACGGTGTCCGTGTGTCCGTGTGTCCGTCGCTGACGACTTTAGTCGCTGACGGTGTCCGTACTTTAGTACTTTAGTTAACCGGTGACTTTAGTGGTGCTCATCGCTGACGCGCTGACGGTGTCCGTTAACCGGTGGTGTCCGTACTTTAGTGGTGCTCATGGTGCTCATTAACCGGTGCGCTGACGGTGTCCGTACTTTAGTTAACCGGTGGTGTCCGTGTGTCCGTTAACCGGTGGTGTCCGTTAACCGGTGCGCTGACGGTGTCCGTGTGTCCGTGTGTCCGTTAACCGGTGTAACCGGTGTAACCGGTGACTTTAGTGTGTCCGTGGTGCTCATCGCTGACGCGCTGACGTAACCGGTGGGTGCTCATCGCTGACGGGTGCTCATGTGTCCGTCGCTGACGACTTTAGTGTGTCCGTGGTGCTCATGTGTCCGTGTGTCCGTTAACCGGTGGGTGCTCATCGCTGACGCGCTGACGACTTTAGTCGCTGACGGGTGCTCATGTGTCCGTTAACCGGTGGTGTCCGTGGTGCTCATGGTGCTCATTAACCGGTGGGTGCTCATGTGTCCGTGTGTCCGTGGTGCTCATCGCTGACGCGCTGACGGTGTCCGTTAACCGGTGGGTGCTCATGTGTCCGTACTTTAGTGGTGCTCATACTTTAGT"
DynamicPatterns(DNA, 13)